title: "Hanan ABSIKE, PhD"
logo: doc/123.jpg
theme: minima  # Simple, elegant GitHub Pages theme
minima:
  skin: dark
description: "Independent Researcher in Theoretical & Experimental Physics"
sass:
  style: compressed
include:
  - assets/css


