title: "Hanan ABSIKE, PhD"
logo: doc1/css/css/hn.jpg
#description: "Physicist | Quantum Transport | Computational Materials"
#author: "Hanan Absike"
#email: "AB.hananham@gmail.com"
#url: "https://hananabsike.github.io"
theme: minima  # Simple, elegant GitHub Pages theme

# Social links (optional)
#github_username: HananAbsike  # Your GitHub username

